disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try
  - line_length
  - identifier_name
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - vertical_whitespace
  - statement_position
  - for_where
  - file_length

opt_in_rules:
  - empty_count
  - empty_string

included:
  - Go Line

excluded:
  - Pods
  - Frameworks
