disabled_rules:
  - todo
  - identifier_name # Game math often uses short vars (x, y, z, i, dt). We'll trust the dev.
  - nesting # SwiftUI often requires deep nesting.

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - collection_alignment
  - fatal_error_message
  - first_where
  - number_separator
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment

included:
  - Go Line

excluded:
  - Pods
  - Frameworks
  - Go LineTests
  - Go LineUITests
  - DerivedData

# Relaxed limits for Game Dev
line_length:
  warning: 150
  error: 200

file_length:
  warning: 800
  error: 1200 # GameScenes can get large

function_body_length:
  warning: 100 # update() loops and UI building can be long
  error: 200

type_body_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 25 # State machines are complex
  error: 40

large_tuple:
  warning: 4
  error: 5

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true